# Generated by Django 3.1.8 on 2024-09-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы ',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('TOP', 'Горячие'), ('COOL', 'Холодные'), ('Netral', 'Нейтральные')], default='Netral', max_length=7),
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='articles',
            name='avtor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.avtor'),
        ),
    ]
