# Generated by Django 3.1.13 on 2024-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20240920_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Комната'),
        ),
    ]
