# Generated by Django 5.0.6 on 2024-08-13 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDROL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='BDUsvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('activ', models.BooleanField(verbose_name='Активный')),
                ('kesh', models.IntegerField(verbose_name='Наличность')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.ManyToManyField(to='usvers.bdrol')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
