# Generated by Django 5.0.6 on 2024-08-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usvers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdusvers',
            name='rol',
        ),
        migrations.AddField(
            model_name='bdusvers',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usvers.bdrol'),
        ),
    ]
