# Generated by Django 5.0.6 on 2024-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usvers', '0002_remove_bdusvers_rol_bdusvers_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdusvers',
            name='infa',
            field=models.FileField(null=True, upload_to='doc/'),
        ),
    ]
