# Generated by Django 5.0.6 on 2024-08-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usvers', '0003_bdusvers_infa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdusvers',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
